name: xUnit

on:
  pull_request:
    branches: ["develop", "main"]
  push:
    branches: ["develop", "main"]

jobs:
  xunit:
    runs-on: self-hosted
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOCKER_HOST: "npipe:////./pipe/docker_engine"

    strategy:
      matrix:
        test_project:
          - Hutzper.Project.Mekiki.Test/Hutzper.Project.Mekiki.Test.csproj
    steps:
      - name: Create .testcontainers.properties
        shell: powershell
        run: |
          $content = 'docker.host=npipe:////./pipe/docker_engine'
          $path = "$env:USERPROFILE\.testcontainers.properties"
          Set-Content -Path $path -Value $content -Encoding ASCII

      - name: Pull PostgreSQL image
        run: docker pull postgres:15

      - name: Run xUnit tests
        run: dotnet test ${{ matrix.test_project }} -r win-x64

      - name: Show Docker info
        run: docker info

      - name: Show Docker container logs
        run: |
          docker ps -a
          docker logs $(docker ps -aq --filter "ancestor=postgres:15") || echo "No container logs"

      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Run xUnit Tests
        run: dotnet test ${{ matrix.test_project }} -r win-x64
