name: DockerTestRunner

on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main", "develop"]

jobs:
  docker-xunit:
    runs-on: self-hosted
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    strategy:
      matrix:
        test_project:
          - Hutzper.Project.Mekiki.Test/Hutzper.Project.Mekiki.Test.csproj
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Create .testcontainers.properties
        shell: powershell
        run: |
          $content = 'docker.host=npipe://./pipe/docker_engine'
          $path = "$env:USERPROFILE\.testcontainers.properties"
          Set-Content -Path $path -Value $content -Encoding ASCII

      - name: Pull PostgreSQL image
        run: docker pull postgres:15

      - name: Run xUnit tests
        run: dotnet test ${{ matrix.test_project }} -r win-x64
