name: xUnit

on:
  pull_request:
    branches: ["develop", "main"]
  push:
    branches: ["develop", "main"]

jobs:
  xunit:
    runs-on: self-hosted
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    strategy:
      matrix:
        test_project:
          - Hutzper.Project.Mekiki.Test/Hutzper.Project.Mekiki.Test.csproj

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Run xUnit Tests
        run: dotnet test ${{ matrix.test_project }} -r win-x64
